### PR TITLE
Updated example sketch and readme

### PR DESCRIPTION
**Pull request by dirrgang**
I was playing with my own monster moto shield and used the example sketch. After working on it to make it suit my needs I figured I could also improve the original sketch a little. 

I added comments taken out of the datasheet of the motor driver to further explain the purpose of the pins and the behaviour of the motor drivers. 

I also made the motorGo function a little more straight forward to understand. 

According to C++ best practices I also removed the preprocessor macros and replaced them with constant values or enums where appropriate.

Lastly I changed the default motor behaviour. In my case I used quite a beefy DC brushed motor, and the rapid oscillation between CW and CCW caused it to jump all over the table. I changed it to be a little more "predictable".

Turn CW for 5s -> Pause for 1s (brake) -> Turn CCW for 5s -> Repeat

This should give an example of rapid direction changing as well as the braking capabilities.

### CODE REVIEW

**Comment by lewispg228** [comment]
Hi @dirrgang and @aneyeforsecrets , 
Thank you for this pull request. At first read through, it looks great. I am hoping to take a closer look at is and get to test this out on some hardware later this week. I will accept the PR asap.

Thanks again!
-Pete

**Comment by lewispg228** [comment]
Hi there @dirrgang and @aneyeforsecrets , 
Thank you for this PR! On initial read-through this looks like good stuff. Your comments with more information from the datasheet are very helpful. Especially in the readme. Also, I did test this out on some hardware and it turns motors as intended - nice work!

However, there are some minor style choices that conflict with our standard practice at SparkFun:

1) We usually like to avoid enums in our example 1 code to make it a bit more accessible to new coders. We certainly use them as necessary in libraries, but we do our best to keep them out of the initial basic Arduino sketch.

2) The "k" prefix for constant variables is something we do not use at SparkFun.

3) We keep setup() and loop() as the first two functions in the code, and all of the remaining functions are placed down below. Again, this is simply a way to make is slightly easier for a new coder.

4) Looks like at line 177, you have a couple variables that are not being used. We usually try to keep the example 1 sketch as clean and as short as possible.

If you are interested in making these adjustments, then we'd be happy to accept your PR.

Let us know and thanks again!
-Pete

**Comment by dirrgang** [comment]
Hello Pete,

thank you for your response! I've made the requested changes and it should adhere to sparkfun coding standards now. I don't have the hardware with me now to run the code, but I'm confident the minor changes I've made shouldn't have introduced any bugs (famous last words).

I also made some more minor modifications to the README.

Looking forward to have my first pull request merged 😄

**Comment by lewispg228** [comment]
Hi @dirrgang ,
Thanks for making these adjustments. Everything looks great. I went ahead and tried it out with some hardware, and it still works!

Congrats on your first PR merge. We appreciate your work on the code and the additions you made.

Thanks again and we hope to see ya on github again sometime soon,
-Pete

**Pull request merged**
